package org.firstinspires.ftc.teamcode.utils.enums;

/**
 * An enum representing the state of an autonomous command.
 */
public enum AutoState {
    RUNNING,
    DRIVE_END,
    SAMPLE_INTAKE_COMPLETE,
    SAMPLE_1_INTAKE_RECOVERED,
    SAMPLE_2_INTAKE_RECOVERED,
    SAMPLE_3_INTAKE_RECOVERED,
    SAMPLE_4_INTAKE_RECOVERED,
    SAMPLE_5_INTAKE_RECOVERED,
    SAMPLE_INTAKE_FAILED,
    NO_TIME,
    PARK,
    SPECIMEN_1_INTAKE_COMPLETE,
    SPECIMEN_2_INTAKE_COMPLETE,
    SPECIMEN_3_INTAKE_COMPLETE,
    SPECIMEN_4_INTAKE_COMPLETE,
    SPECIMEN_5_INTAKE_COMPLETE,
    SPECIMEN_1_DROP_COMPLETE,
    SPECIMEN_2_DROP_COMPLETE,
    SPECIMEN_3_DROP_COMPLETE,
    SPECIMEN_4_DROP_COMPLETE,
    SPECIMEN_5_DROP_COMPLETE,
    TIMEOUT,
    FAILED_SAMPLE_1_TIMEOUT,
    FAILED_SAMPLE_2_TIMEOUT,
    FAILED_SAMPLE_3_TIMEOUT,
    FAILED_SAMPLE_4_TIMEOUT,
    FAILED_SAMPLE_5_TIMEOUT,
}
